services:
  setup:
    image: usterkify/setup:0.1.0-SNAPSHOT
    networks:
      - my-network

  api:
    image: usterkify/api:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - my-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
